"""Initial

Revision ID: f28fc6a37ea6
Revises: 
Create Date: 2025-03-11 16:27:31.985592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28fc6a37ea6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('banners_category_id_fkey', 'banners', type_='foreignkey')
    op.drop_constraint('banners_subcategory_id_fkey', 'banners', type_='foreignkey')
    op.create_foreign_key(None, 'banners', 'subcategories', ['subcategory_id'], ['id'])
    op.create_foreign_key(None, 'banners', 'categories', ['category_id'], ['id'])
    op.create_unique_constraint(None, 'subcategories', ['name'])
    op.drop_constraint('subcategories_category_id_fkey', 'subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'subcategories', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.create_foreign_key('subcategories_category_id_fkey', 'subcategories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'subcategories', type_='unique')
    op.drop_constraint(None, 'banners', type_='foreignkey')
    op.drop_constraint(None, 'banners', type_='foreignkey')
    op.create_foreign_key('banners_subcategory_id_fkey', 'banners', 'subcategories', ['subcategory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('banners_category_id_fkey', 'banners', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
